#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  hcsr501.py
#  
#  Copyright 2021  <pi@raspberrypi>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

import RPi.GPIO as GPIO
import time


GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
led_B=20
led_R=21
sensor=17

GPIO.setup(led_R, GPIO.OUT)
GPIO.setup(led_B, GPIO.OUT)
GPIO.setup(sensor, GPIO.IN)

print("PIR ready")
time.sleep(2)
try:
    while True:
        if GPIO.input(sensor) ==1:
            GPIO.output(led_B, 1)
            GPIO.output(led_R, 0)
            print("motion detected")
            time.sleep(0.1)
            
        if GPIO.input(sensor) ==0:
            GPIO.output(led_B, 0)
            GPIO.output(led_R, 1)
            time.sleep(0.1)    

except KeyboardInterrupt:
    print("stopped by user")
    GPIO.cleanup()

#센서 동작 미흡 
